# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      ['jekyll-paginate']

# Conversion
markdown:     redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     /blog/:year/:month/:day/:title
paginate_path: /blog/:num
paginate:      5
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

## jekyll-assets: ##
# see more at https://github.com/ixti/jekyll-assets
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

minfy_html: true

## Company ##
company:
  address:
    street:    "1027 E. Washington St. #107"
    city:      Phoenix
    state:     AZ
    zip:       85034
  cover_image: blog-cover.jpg
  description: Velocity Labs specializes in custom web application development using Ruby on Rails.
  social:
    github:    velocity-labs
    twitter:   velocitylabs
  logo:        logo.png
  name:        Velocity Labs
  phone:       (602) 633-5049
  subtitle:    Ruby on Rails Developers | Custom Software Solutions
  url:         http://velocitylabs.io/

## Blog ##
blog:
  title:    The Lab Notebook
  subtitle: "brought to you by <a href=\"http://velocitylabs.io/\">Velocity Labs</a>"
